### PR TITLE
Prep for version 1

### PR DESCRIPTION
**Pull request by brockfanning**
This PR includes:
* Config updates for the latest Open SDG code
* Updates to include files, layouts, and styles to mesh with recent Open SDG changes
* Removal of some auto-generated files

This will likely fail automated tests, because it depends on changes to the translations and data repos:
* https://github.com/GSA/sdg-data-usa/pull/169
* https://github.com/GSA/sdg-translations/pull/5

### CODE REVIEW

**Comment by adborden** [comment]
@brockfanning thanks for starting this! We were just talking about taking on this work https://github.com/GSA/datagov-deploy/issues/1243

I'll push this to Federalist for preview and take a look.

**Comment by brockfanning** [comment]
@adborden No problem. A couple updates:
1. We've just released a new tag for open-sdg, 1.0.0-rc2, which you could point to instead of the "master" which I have in this PR. (Happy to update that in PR if you'd like.)
2. Looks like the PR has a conflict now - let me know if you'd like me to resolve that conflict.

**Comment by brockfanning** [comment]
@adborden @philipashlock Another update - we have included a bit more refactoring into the upcoming 1.0.0 release. The latest tag is 1.0.0-beta3. It will require some updates to this PR. I'll go ahead and rebase the PR to make those updates, unless you object.

**Comment by brockfanning** [comment]
@adborden @philipashlock 
I've rebased to resolve the conflict, and also updated to the latest version of Open SDG as of this writing: 1.1.0. I'm not sure what's going on with the CircleCI failure.

**Comment by adborden** [comment]
@brockfanning it looks like a git hiccup, try re-running your CI job.

**Comment by adborden** [comment]
... spoke to soon, `bundle exec jekyll build` is failing for me:
```
$ bundle exec jekyll build
Configuration file: /Users/aarondborden/projects/datagov/sdg-indicators-usa/_config.yml
            Source: /Users/aarondborden/projects/datagov/sdg-indicators-usa
       Destination: /Users/aarondborden/projects/datagov/sdg-indicators-usa/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
      Remote Theme: Using theme open-sdg/open-sdg
404 Not Found
Unable to read data from: https://gsa.github.io/sdg-data-usa/prod/stats/reporting.json
```

And sure enough, I'm not seeing any /stats/reporting.json on the [gh-pages branch of GSA/sdg-data-usa](https://github.com/GSA/sdg-data-usa/tree/gh-pages/prod). I'm not sure who owns that repo, I don't even have write access.

**Comment by brockfanning** [comment]
@adborden I think this needs another rebase. The test failures now are likely because this is a really a three-part pull request - see the links in the PR description. I'm not sure what the specifics are now for deployment workflows, but I suspect this PR will be tricky to test. In the meantime I'll try another rebase to keep it current.

**Comment by adborden** [comment]
Yeah, same error.

Is it possible to add a configuration so that we can point to the updated branches? That way we can build and test without having to merge everything and 🤞

**Comment by brockfanning** [comment]
The challenge is that [this PR](https://github.com/GSA/sdg-data-usa/pull/169) of the [data repository](https://github.com/GSA/sdg-data-usa) needs to be built and deployed. But obviously we don't want to merge that PR without testing. Do you know if there is any mechanism for deploying feature branches of the sdg-data-usa repository? Not sure if sdg-data-usa is wired into the Federalist stuff or not. If not, I could see if I can deploy a build of my branch using my fork.

Once we have a build of that PR deployed somewhere, then yes we can update this PR to point there, at which point it should pass tests.

**Comment by btylerburton** [comment]
Closing as outdated

**Pull request closed without merging**
